# Generated by Django 2.2.7 on 2019-11-06 21:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoesCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=200)),
                ('sigla_pais', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DadosClimaticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura_atual', models.FloatField()),
                ('temperatura_minima', models.FloatField()),
                ('temperatura_maxima', models.FloatField()),
                ('velocidade_vento', models.IntegerField()),
                ('umidade_relativa_ar', models.IntegerField()),
                ('volume_chuva', models.IntegerField()),
                ('detalhes', models.CharField(max_length=100)),
                ('medicoes_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MedicoesCidade')),
            ],
        ),
    ]
