# Generated by Django 2.2.7 on 2019-11-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191106_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='detalhes',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='temperatura_atual',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='temperatura_maxima',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='temperatura_minima',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='umidade_relativa_ar',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='velocidade_vento',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='volume_chuva',
            field=models.IntegerField(default=None),
        ),
    ]
