# Generated by Django 2.2.7 on 2019-11-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191106_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='detalhes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='temperatura_atual',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='temperatura_maxima',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='temperatura_minima',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='umidade_relativa_ar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='velocidade_vento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='volume_chuva',
            field=models.IntegerField(),
        ),
    ]
