# Generated by Django 2.2.7 on 2019-11-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191106_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='data_medicao',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='nascer_sol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='por_sol',
            field=models.CharField(max_length=10),
        ),
    ]
