# Generated by Django 2.2.7 on 2019-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dadosclimaticos_hora_medicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosclimaticos',
            name='nascer_sol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
